[general]
working_directory = "C:/Users/humti"

[terminal.shell]
program = "pwsh"
args = ["-NoLogo", "-NoProfile"]

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 10
