[general]
working_directory = "C:/Users/humti"
import = [
    "./cyberpunkNeon-Theme.toml",
    "./font.toml",
    "./terminal.toml",
    "./window.toml",
    "./keyboard.toml",
]

# LIKES
# ./cyberpunkNeon-Theme.toml
